spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: http://github.com/MichaelYgZhang/Stone/config-repo/
#          search-paths: repo
#          username:
#          password:

server:
  port: 1201