zuul:
  prefix: /api
  routes:
    service1:
      path: /service1Api/**
      serviceId: service1
    service2:
      path: /service2Api/**
      serviceId: service2

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    registerWithEureka: false
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service
